version: '3.1'

services:
  zoo1:
    image: zookeeper:3.7.0
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
      - 8081:8080
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_CFG_EXTRA: localSessionsEnabled=true
    volumes:
      - ./zoo1/data_faulty:/data:rw
      # - ./zoo1/data:/data:rw
      - ./zoo1/datalog:/datalog:rw
    
  zoo2:
    image: zookeeper:3.7.0
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
      - 8082:8080
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_CFG_EXTRA: localSessionsEnabled=true
    volumes:
      - ./zoo2/data:/data:rw
      - ./zoo2/datalog:/datalog:rw

  zoo3:
    image: zookeeper:3.7.0
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
      - 8083:8080
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_CFG_EXTRA: localSessionsEnabled=true
    volumes:
      - ./zoo3/data:/data:rw
      - ./zoo3/datalog:/datalog:rw